spring.mail.host=smtp-mail.outlook.com
spring.mail.port=587
spring.mail.username=BerryStreet_Boxjelly@outlook.com
spring.mail.password=ofhYi7DivR

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true